### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by craftzdog** [wooorm/trim-trailing-lines#4]
After updating to 2.0.0:

```js
export function trimTrailingLines(value) {
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by wooorm** [comment]
Yup, as mentioned in the v2 changelog, this package is now ESM only.
I’ve just added a link with more information to the readme too!

**Comment by craftzdog** [comment]
Oops sorry, I missed it. Thanks!
